openapi: 3.0.3
info:
  title: Voting App API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/
  - url: http://localhost:8080/
paths:
  /authentication/login:
    post:
      summary: Attempt to log in as admin
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginData'
      responses:
        '200':
          description: 'Login successful'
        '401':
          description: 'Login failed'
  /authentication/logout:
    post:
      summary: Log out
      responses:
        '200':
          description: Successfully logged out
components:
  schemas:
    LoginData:
      type: object
      properties:
        username:
          type: string
          example: admin
        password:
          type: string
          example: password
    Quiz:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: 'Quiz 1'
        description:
          type: string
          example: 'This is a quiz'
        thumbnail:
          type: string
          example: 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'
    Question:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        text:
          type: string
          example: 'What is the capital of France?'
        time:
          type: integer
          format: int32
          example: 10
        points:
          type: integer
          format: int32
          example: 10
        answers:
          type: array
          items:
              $ref: '#/components/schemas/Answer'
    Answer:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 1
          text:
            type: string
            example: 'Paris'
          correct:
            type: boolean
            example: true
          order:
            type: integer
            format: int64
            example: 1